name: Reusable - common pipeline

on:
  workflow_call:
    inputs:
      env:
        description: "Environment"
        type: string
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show inputs
        run: echo "Running for ${{ inputs.env }}"
