name: Pipeline for Repo A
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: false
        type: choice

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running for ${{ github.event.inputs.env }}"
